[workspace]
resolver = "2"
members = [
    "crates/tofy-spec",
    "crates/tofy-macros",
    "crates/tofy",
    "examples/infra",
    "examples/infra-tofu",
    "examples/infra-aws",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/hexuria/tofy"
authors = ["Uriah Galang"]

[workspace.dependencies]
serde = { version = "=1.0.217", features = ["derive"] }
serde_json = "=1.0.138"
thiserror = "=2.0.12"
tofy-spec = { path = "crates/tofy-spec" }
tofy-macros = { path = "crates/tofy-macros" }
